services:
  - type: web
    name: discord-bot
    env: node
    buildCommand: bash ./render-build.sh
    startCommand: npm run start
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    plan: free